<!DOCTYPE html>
<html lang="en">
<head>
	<title>the odd one out</title>
	<meta charset="utf-8">
	<link rel="stylesheet"  href="css/styles.css">
	<link rel="stylesheet" href="css/coin-slider-styles.css" type="text/css" />
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lobster" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>