<script src="https://code.jquery.com/jquery.js"></script>
<script src="js/menu-highlighter.js"></script>

<script type="text/javascript" src="jquery-1.4.2.js"></script>
<script type="text/javascript" src="js/coin-slider.min.js"></script>

<script type="text/javascript">
  $(document).ready(function() {
    $('#coin-slider').coinslider({width: window.innerWidth, effect: 'straight', spw: 1, sph: 1});
  });
</script>
