	<div id='coin-slider' class="card shadow carousel slide col-8" data-ride="carousel" >
	  <a href="amanda.php">
	    <img class="rounded" src='images/amanda.jpg' >
	    <span>
	      Amanda
	    </span>
	  </a>

	  <a href="ding.php">
	    <img class="rounded" src='images/ding.jpg' >
	    <span>
	      Ding
	    </span>
	  </a>

	  <a href="jack.php">
	    <img class="rounded" src='images/jack.jpg' >
	    <span>
	      Jack
	    </span>
	  </a>
	</div>
