	<div id='coin-slider'>
	  <a href="index.php" target="_blank">
	    <img class="rounded" src='images/odd.jpg' >
	    <span>
	      Home
	    </span>
	  </a>
	  
	  <a href="amanda.php">
	    <img class="rounded" src='images/amanda.jpg' >
	    <span>
	      Amanda
	    </span>
	  </a>

	  <a href="ding.php">
	    <img class="rounded" src='images/ding.jpg' >
	    <span>
	      Ding
	    </span>
	  </a>

	  <a href="jack.php">
	    <img class="rounded" src='images/jack.jpg' >
	    <span>
	      Jack
	    </span>
	  </a>
	</div>