	<div id='coin-slider' class="card shadow carousel slide" data-ride="carousel" >
	  <a  href="index.php" target="_blank">
	    <img class="rounded" alt="Home" src='images/odd.jpg' >
	    <span>
	      Home
	    </span>
	  </a>

	  <a href="ding.php">
	    <img class="rounded" alt="Ding" src='images/ding.jpg' >
	    <span>
	      Ding
	    </span>
	  </a>

	  <a href="amanda.php">
	    <img class="rounded" alt="Amanda" src='images/amanda.jpg' >
	    <span>
	      Amanda
	    </span>
	  </a>

	  <a href="jack.php">
	    <img class="rounded" alt="Jack" src='images/jack.jpg' >
	    <span>
	      Jack
	    </span>
	  </a>
	</div>
